# stable/Dockerfile
#
# Build a Podman container image from the latest
# stable version of Podman on the Fedoras Updates System.
# https://bodhi.fedoraproject.org/updates/?search=podman
# This image can be used to create a secured container
# that runs safely with privileges within the container.
#
FROM registry.fedoraproject.org/fedora:latest

# Don't include container-selinux and remove
# directories used by yum that are just taking
# up space.
RUN dnf -y update && rpm --setcaps shadow-utils 2>/dev/null && dnf -y install podman fuse-overlayfs --exclude container-selinux && dnf clean all && rm -rf /var/cache /var/log/dnf* /var/log/yum.*

RUN useradd podman; echo -e "podman:1:999\npodman:1001:64535" > /etc/subuid; echo -e "podman:1:999\npodman:1001:64535" > /etc/subgid;

ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/containers.conf /etc/containers/containers.conf
ADD https://raw.githubusercontent.com/containers/libpod/master/contrib/podmanimage/stable/podman-containers.conf /home/podman/.config/containers/containers.conf

RUN mkdir -p /home/podman/.local/share/containers && chown podman:podman -R /home/podman && chmod 644 /etc/containers/containers.conf

RUN sed -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' /usr/share/containers/storage.conf > /etc/containers/storage.conf

VOLUME /home/podman/.local/share/containers
VOLUME /var/lib/containers

RUN mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers /var/lib/shared/vfs-images /var/lib/shared/vfs-layers && touch /var/lib/shared/overlay-images/images.lock && touch /var/lib/shared/overlay-layers/layers.lock && touch /var/lib/shared/vfs-images/images.lock && touch /var/lib/shared/vfs-layers/layers.lock

##----------------------------------
# Install git command line
#
RUN dnf install -y git
##----------------------------------

##----------------------------------
# Install the OpenShift oc command line
#
RUN curl -sL -o /tmp/oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz && \
tar -C /tmp -xf /tmp/oc.tar.gz --no-same-owner && \
mv /tmp/oc /usr/local/bin && \
chmod +x /usr/local/bin/oc && \
rm /tmp/*
##----------------------------------


##----------------------------------
# Install node and npm
#
RUN dnf -y install npm container-selinux
##----------------------------------

##----------------------------------
# Install jq
#
RUN dnf -y install jq container-selinux
##----------------------------------

RUN curl -sLk https://github.com/yudai/gotty/releases/download/v1.0.1/gotty_linux_amd64.tar.gz | tar xzC /usr/local/bin

RUN mkdir /.local && chmod -R 777 /.local

RUN mkdir /workspace && chmod 777 workspace

RUN chmod 777 /var/lib/containers

WORKDIR /workspace

USER podman

ENTRYPOINT ["/usr/local/bin/gotty"]
CMD ["-w","bash"]
